"""Pre-built checklist templates for SRO and FINMA licensing pathways."""

from src.models.client import ChecklistItem


def _item(
    id: str,
    category: str,
    item: str,
    required_for: str,
    estimated_days: int | None = None,
    depends_on: list[str] | None = None,
) -> ChecklistItem:
    return ChecklistItem(
        id=id,
        category=category,
        item=item,
        required_for=required_for,
        estimated_days=estimated_days,
        depends_on=depends_on or [],
    )


def get_sro_checklist() -> list[ChecklistItem]:
    return [
        # Legal structure & corporate
        _item(
            "sro-01", "legal_structure", "Register legal entity (AG or GmbH)", "sro", 14
        ),
        _item(
            "sro-02",
            "legal_structure",
            "Establish Swiss office address",
            "sro",
            7,
            ["sro-01"],
        ),
        _item(
            "sro-03",
            "personnel",
            "Appoint Swiss-resident director with signing authority",
            "sro",
            14,
            ["sro-01"],
        ),
        _item(
            "sro-04",
            "capital",
            "Meet minimum capital requirements (corporate law minimums)",
            "sro",
            7,
            ["sro-01"],
        ),
        _item("sro-05", "capital", "Open Swiss bank account", "sro", 21, ["sro-01"]),
        # Corporate documentation
        _item(
            "sro-06",
            "documentation",
            "Prepare articles of association and shareholder register",
            "sro",
            7,
            ["sro-01"],
        ),
        _item(
            "sro-07",
            "documentation",
            "Obtain commercial register extract (not older than 3 months)",
            "sro",
            3,
            ["sro-01"],
        ),
        _item(
            "sro-08",
            "documentation",
            "Prepare business model description and service offering details",
            "sro",
            14,
        ),
        _item(
            "sro-09",
            "documentation",
            "Prepare ownership structure diagram down to UBOs",
            "sro",
            7,
            ["sro-01"],
        ),
        _item(
            "sro-10",
            "documentation",
            "Gather source of funds documentation for 10%+ shareholders",
            "sro",
            14,
            ["sro-09"],
        ),
        # Personnel & governance
        _item(
            "sro-11",
            "compliance",
            "Appoint qualified AML compliance officer (Swiss-resident)",
            "sro",
            14,
        ),
        _item(
            "sro-12",
            "compliance",
            "Engage FINMA-recognized external AML auditor",
            "sro",
            14,
        ),
        _item(
            "sro-13",
            "personnel",
            "Prepare CVs and credentials for all key personnel",
            "sro",
            7,
            ["sro-03"],
        ),
        _item(
            "sro-14",
            "personnel",
            "Obtain criminal record certificates for key persons",
            "sro",
            14,
            ["sro-03"],
        ),
        _item(
            "sro-15",
            "personnel",
            "Obtain ID documents and professional references for directors",
            "sro",
            7,
            ["sro-03"],
        ),
        # AML framework
        _item(
            "sro-16",
            "compliance",
            "Draft AML/KYC policies and CDD/EDD procedures",
            "sro",
            21,
            ["sro-11"],
        ),
        _item(
            "sro-17",
            "compliance",
            "Implement transaction monitoring system",
            "sro",
            30,
            ["sro-16"],
        ),
        _item(
            "sro-18",
            "compliance",
            "Implement sanctions screening (SECO, UN, EU lists)",
            "sro",
            14,
            ["sro-16"],
        ),
        _item(
            "sro-19",
            "compliance",
            "Establish PEP screening and SAR reporting to MROS",
            "sro",
            7,
            ["sro-16"],
        ),
        _item(
            "sro-20",
            "compliance",
            "Draft risk assessment framework (business and client risk)",
            "sro",
            14,
            ["sro-16"],
        ),
        _item(
            "sro-21",
            "compliance",
            "Establish record keeping policy (10-year retention)",
            "sro",
            7,
            ["sro-16"],
        ),
        # VASP-specific (if applicable)
        _item(
            "sro-22",
            "compliance",
            "Prepare token type analysis and classification",
            "sro",
            7,
        ),
        _item(
            "sro-23",
            "compliance",
            "Document wallet management and hot/cold storage policies",
            "sro",
            14,
        ),
        _item(
            "sro-24",
            "compliance",
            "Integrate blockchain analytics and Travel Rule compliance",
            "sro",
            21,
            ["sro-16"],
        ),
        # IT & operations
        _item(
            "sro-25",
            "it_operations",
            "Prepare IT security documentation",
            "sro",
            14,
        ),
        _item(
            "sro-26",
            "it_operations",
            "Prepare AML training records for staff",
            "sro",
            7,
            ["sro-16"],
        ),
        # Governance check
        _item(
            "sro-27",
            "governance",
            "Assess FINMA license triggers (client assets, order book, deposits)",
            "sro",
            7,
        ),
        # Application
        _item(
            "sro-28",
            "application",
            "Complete SRO application form (Beitrittsgesuch)",
            "sro",
            7,
            [
                "sro-02",
                "sro-03",
                "sro-04",
                "sro-05",
                "sro-12",
                "sro-16",
                "sro-20",
            ],
        ),
        _item(
            "sro-29",
            "application",
            "Pay SRO deposit fee (approx. CHF 5,000)",
            "sro",
            1,
            ["sro-28"],
        ),
        _item(
            "sro-30",
            "application",
            "SRO review period (2-6 weeks)",
            "sro",
            42,
            ["sro-29"],
        ),
        _item(
            "sro-31",
            "application",
            "Address SRO feedback and questions",
            "sro",
            14,
            ["sro-30"],
        ),
    ]


def get_finma_checklist() -> list[ChecklistItem]:
    return [
        # Legal structure
        _item(
            "fin-01",
            "legal_structure",
            "Register legal entity (AG or GmbH)",
            "finma",
            14,
        ),
        _item(
            "fin-02",
            "legal_structure",
            "Establish Swiss office address",
            "finma",
            7,
            ["fin-01"],
        ),
        _item(
            "fin-03",
            "legal_structure",
            "Obtain commercial register extract",
            "finma",
            7,
            ["fin-01"],
        ),
        # Ownership & structure
        _item(
            "fin-04",
            "documentation",
            "Prepare share capital structure and shareholder register",
            "finma",
            7,
            ["fin-01"],
        ),
        _item(
            "fin-05",
            "documentation",
            "Complete qualified participation forms (10%+ holders)",
            "finma",
            7,
            ["fin-04"],
        ),
        _item(
            "fin-06",
            "documentation",
            "Prepare beneficial ownership declaration and group structure",
            "finma",
            7,
            ["fin-04"],
        ),
        # Personnel & governance
        _item(
            "fin-07",
            "personnel",
            "Appoint Swiss-resident director(s)",
            "finma",
            14,
            ["fin-01"],
        ),
        _item(
            "fin-08",
            "governance",
            "Establish board of directors (composition, committees)",
            "finma",
            21,
            ["fin-01"],
        ),
        _item(
            "fin-09",
            "governance",
            "Appoint qualified executive management team",
            "finma",
            30,
            ["fin-08"],
        ),
        _item(
            "fin-10",
            "governance",
            "Complete FINMA personal questionnaires for all key persons",
            "finma",
            14,
            ["fin-09"],
        ),
        _item(
            "fin-11",
            "personnel",
            "Gather ID documents, residence permits, signed CVs for all key persons",
            "finma",
            14,
            ["fin-09"],
        ),
        _item(
            "fin-12",
            "personnel",
            "Obtain criminal record and debt enforcement extracts (< 3 months old)",
            "finma",
            14,
            ["fin-09"],
        ),
        _item(
            "fin-13",
            "governance",
            "Complete fit-and-proper declarations (Gewaehrsformular)",
            "finma",
            7,
            ["fin-09"],
        ),
        _item(
            "fin-14",
            "governance",
            "Prepare conflicts of interest policy and signing authority matrix",
            "finma",
            14,
            ["fin-08"],
        ),
        # Capital
        _item(
            "fin-15",
            "capital",
            "Meet minimum capital requirements for license type",
            "finma",
            14,
            ["fin-01"],
        ),
        _item(
            "fin-16",
            "capital",
            "Open Swiss bank account and deposit capital",
            "finma",
            21,
            ["fin-15"],
        ),
        # Compliance
        _item("fin-17", "compliance", "Appoint compliance officer", "finma", 14),
        _item("fin-18", "compliance", "Appoint risk officer", "finma", 14),
        _item(
            "fin-19",
            "compliance",
            "Establish internal audit function",
            "finma",
            21,
            ["fin-17"],
        ),
        _item(
            "fin-20",
            "compliance",
            "Engage FINMA-recognized external auditor",
            "finma",
            14,
        ),
        _item(
            "fin-21",
            "compliance",
            "Draft comprehensive AML/CFT framework and KYC procedures",
            "finma",
            30,
            ["fin-17"],
        ),
        _item(
            "fin-22",
            "compliance",
            "Implement transaction monitoring system",
            "finma",
            30,
            ["fin-21"],
        ),
        _item(
            "fin-23",
            "compliance",
            "Implement sanctions screening (SECO, UN, EU)",
            "finma",
            14,
            ["fin-21"],
        ),
        # Organizational & documentation
        _item(
            "fin-24",
            "documentation",
            "Prepare organizational chart with FTEs per unit",
            "finma",
            7,
            ["fin-09"],
        ),
        _item(
            "fin-25",
            "documentation",
            "Prepare risk & compliance framework documentation",
            "finma",
            21,
            ["fin-18"],
        ),
        _item(
            "fin-26",
            "documentation",
            "Document outsourcing arrangements with contracts",
            "finma",
            14,
        ),
        _item(
            "fin-27",
            "documentation",
            "Prepare deposit segregation documentation (Art. 7a BO)",
            "finma",
            7,
            ["fin-21"],
        ),
        # Business plan & financials
        _item(
            "fin-28",
            "application",
            "Prepare comprehensive business plan with 3-year projections",
            "finma",
            30,
            ["fin-09"],
        ),
        # IT & operations
        _item(
            "fin-29",
            "it_operations",
            "Draft IT security policy and cybersecurity framework",
            "finma",
            21,
        ),
        _item(
            "fin-30",
            "it_operations",
            "Prepare business continuity and disaster recovery plan",
            "finma",
            14,
        ),
        _item(
            "fin-31",
            "it_operations",
            "Document core banking/IT systems and data architecture",
            "finma",
            14,
        ),
        _item(
            "fin-32",
            "it_operations",
            "Prepare data protection policy (GDPR/Swiss DPA)",
            "finma",
            7,
        ),
        _item(
            "fin-33",
            "it_operations",
            "Document KYC/AML system technical specifications",
            "finma",
            14,
            ["fin-21"],
        ),
        _item(
            "fin-34",
            "it_operations",
            "Complete vendor due diligence for critical service providers",
            "finma",
            14,
        ),
        # Audit
        _item(
            "fin-35",
            "application",
            "Obtain audit mandate acceptance from regulatory audit firm",
            "finma",
            7,
            ["fin-20"],
        ),
        # Application
        _item("fin-36", "application", "Register on FINMA EHP platform", "finma", 1),
        _item(
            "fin-37",
            "application",
            "Complete and submit FINMA application forms via EHP",
            "finma",
            14,
            [
                "fin-06",
                "fin-13",
                "fin-16",
                "fin-20",
                "fin-21",
                "fin-25",
                "fin-28",
                "fin-29",
                "fin-35",
                "fin-36",
            ],
        ),
        _item(
            "fin-38",
            "application",
            "FINMA assessment period (4-12 months)",
            "finma",
            180,
            ["fin-37"],
        ),
    ]


def get_securities_firm_checklist() -> list[ChecklistItem]:
    """Checklist for Securities Firm License (FinIA) — CHF 1.5M+ capital."""
    return [
        # Legal & corporate
        _item(
            "sec-01",
            "legal_structure",
            "Register legal entity (AG, Kommandit-AG, or GmbH)",
            "finma",
            14,
        ),
        _item(
            "sec-02",
            "legal_structure",
            "Prepare articles specifying securities types, markets, clients",
            "finma",
            14,
            ["sec-01"],
        ),
        _item(
            "sec-03",
            "legal_structure",
            "Prepare business rules (internal regulations governing operations)",
            "finma",
            14,
            ["sec-01"],
        ),
        _item(
            "sec-04",
            "legal_structure",
            "Obtain commercial register extract",
            "finma",
            7,
            ["sec-01"],
        ),
        # Capital — higher requirements
        _item(
            "sec-05",
            "capital",
            "Deposit minimum capital of CHF 1.5 million fully paid-up",
            "finma",
            21,
            ["sec-01"],
        ),
        _item(
            "sec-06",
            "capital",
            "Prepare capital adequacy calculation (Art. 63 FinIO)",
            "finma",
            14,
            ["sec-05"],
        ),
        _item(
            "sec-07",
            "capital",
            "Prepare risk diversification analysis (concentration limits)",
            "finma",
            14,
            ["sec-05"],
        ),
        # Ownership
        _item(
            "sec-08",
            "documentation",
            "Prepare shareholder structure and qualified participation forms",
            "finma",
            7,
            ["sec-01"],
        ),
        _item(
            "sec-09",
            "documentation",
            "Prepare beneficial ownership declaration and group structure",
            "finma",
            7,
            ["sec-08"],
        ),
        _item(
            "sec-10",
            "documentation",
            "Obtain foreign control documentation (reciprocity guarantee)",
            "finma",
            21,
            ["sec-09"],
        ),
        # Governance & personnel (fit & proper)
        _item(
            "sec-11",
            "governance",
            "Establish board of directors (chairman, committees)",
            "finma",
            21,
            ["sec-01"],
        ),
        _item(
            "sec-12",
            "governance",
            "Appoint executive management with Swiss presence",
            "finma",
            30,
            ["sec-11"],
        ),
        _item(
            "sec-13",
            "personnel",
            "Complete FINMA personal questionnaires for all key persons",
            "finma",
            14,
            ["sec-12"],
        ),
        _item(
            "sec-14",
            "personnel",
            "Gather IDs, CVs, criminal records, debt extracts, qualifications",
            "finma",
            14,
            ["sec-12"],
        ),
        _item(
            "sec-15",
            "governance",
            "Complete fit-and-proper declarations (Gewaehrsformular)",
            "finma",
            7,
            ["sec-12"],
        ),
        # Organizational structure
        _item(
            "sec-16",
            "governance",
            "Prepare org chart with function separation (trading/settlement)",
            "finma",
            14,
            ["sec-12"],
        ),
        _item(
            "sec-17",
            "governance",
            "Prepare job descriptions and staffing plan",
            "finma",
            7,
            ["sec-12"],
        ),
        _item(
            "sec-18",
            "governance",
            "Document all outsourced functions with contracts",
            "finma",
            14,
        ),
        # Risk management framework
        _item(
            "sec-19",
            "compliance",
            "Draft comprehensive risk management policy",
            "finma",
            21,
        ),
        _item(
            "sec-20",
            "compliance",
            "Prepare market, credit, and settlement risk controls",
            "finma",
            21,
            ["sec-19"],
        ),
        _item(
            "sec-21",
            "compliance",
            "Prepare liquidity risk management and stress testing",
            "finma",
            14,
            ["sec-19"],
        ),
        _item(
            "sec-22",
            "compliance",
            "Prepare operational and legal risk management documentation",
            "finma",
            14,
            ["sec-19"],
        ),
        # Internal controls
        _item(
            "sec-23",
            "compliance",
            "Establish internal control framework (three lines of defense)",
            "finma",
            21,
            ["sec-19"],
        ),
        _item(
            "sec-24",
            "compliance",
            "Set up internal audit function with charter and annual plan",
            "finma",
            14,
            ["sec-23"],
        ),
        _item(
            "sec-25",
            "compliance",
            "Appoint compliance function for monitoring",
            "finma",
            14,
        ),
        # FinSA conduct requirements
        _item(
            "sec-26",
            "compliance",
            "Prepare client classification (Retail/Professional/Institutional)",
            "finma",
            14,
            ["sec-25"],
        ),
        _item(
            "sec-27",
            "compliance",
            "Draft best execution policy and order handling procedures",
            "finma",
            14,
            ["sec-25"],
        ),
        _item(
            "sec-28",
            "compliance",
            "Draft conflicts of interest policy and register",
            "finma",
            14,
            ["sec-25"],
        ),
        _item(
            "sec-29",
            "compliance",
            "Prepare client information documents and KIDs",
            "finma",
            14,
            ["sec-26"],
        ),
        # AML
        _item(
            "sec-30",
            "compliance",
            "Draft AML/KYC policy and CDD procedures",
            "finma",
            21,
            ["sec-25"],
        ),
        _item(
            "sec-31",
            "compliance",
            "Implement transaction monitoring and sanctions screening",
            "finma",
            30,
            ["sec-30"],
        ),
        _item(
            "sec-32",
            "compliance",
            "Implement market abuse prevention controls",
            "finma",
            14,
            ["sec-30"],
        ),
        # Trading & operations
        _item(
            "sec-33",
            "it_operations",
            "Document trading system and settlement procedures",
            "finma",
            21,
        ),
        _item(
            "sec-34",
            "it_operations",
            "Prepare safekeeping procedures for client asset segregation",
            "finma",
            14,
        ),
        _item(
            "sec-35",
            "it_operations",
            "Set up position limits and trading controls",
            "finma",
            7,
            ["sec-33"],
        ),
        # IT & security
        _item(
            "sec-36",
            "it_operations",
            "Draft IT security policy and cybersecurity controls",
            "finma",
            21,
        ),
        _item(
            "sec-37",
            "it_operations",
            "Prepare business continuity and incident response plans",
            "finma",
            14,
        ),
        # Business plan
        _item(
            "sec-38",
            "application",
            "Prepare comprehensive business plan with financial projections",
            "finma",
            30,
            ["sec-12"],
        ),
        _item(
            "sec-39",
            "application",
            "Prepare product documentation (securities/derivatives to be traded)",
            "finma",
            14,
            ["sec-38"],
        ),
        # Audit
        _item(
            "sec-40",
            "application",
            "Appoint licensing audit firm and regulatory audit firm",
            "finma",
            14,
        ),
        # Application
        _item("sec-41", "application", "Register on FINMA EHP platform", "finma", 1),
        _item(
            "sec-42",
            "application",
            "Complete and submit FINMA securities firm application via EHP",
            "finma",
            14,
            [
                "sec-06",
                "sec-09",
                "sec-15",
                "sec-23",
                "sec-30",
                "sec-38",
                "sec-40",
                "sec-41",
            ],
        ),
        _item(
            "sec-43",
            "application",
            "FINMA assessment period (4-10 months)",
            "finma",
            180,
            ["sec-42"],
        ),
    ]


def get_payment_systems_checklist() -> list[ChecklistItem]:
    """Checklist for Payment Systems Operator (FinfraG) — systemic risk focus."""
    return [
        # Legal & corporate
        _item(
            "pso-01",
            "legal_structure",
            "Register Swiss legal entity with appropriate articles",
            "finma",
            14,
        ),
        _item(
            "pso-02",
            "legal_structure",
            "Obtain commercial register extract",
            "finma",
            7,
            ["pso-01"],
        ),
        _item(
            "pso-03",
            "documentation",
            "Prepare ownership structure to beneficial owners",
            "finma",
            7,
            ["pso-01"],
        ),
        # Governance
        _item(
            "pso-04",
            "governance",
            "Establish board and management with fit-and-proper documentation",
            "finma",
            21,
            ["pso-01"],
        ),
        _item(
            "pso-05",
            "governance",
            "Prepare proper business conduct declarations for all key persons",
            "finma",
            7,
            ["pso-04"],
        ),
        _item(
            "pso-06",
            "governance",
            "Establish internal control framework (three lines of defense)",
            "finma",
            21,
            ["pso-04"],
        ),
        # Business plan & model
        _item(
            "pso-07",
            "application",
            "Prepare comprehensive system description and operations programme",
            "finma",
            30,
        ),
        _item(
            "pso-08",
            "application",
            "Prepare business plan with financial projections and growth strategy",
            "finma",
            21,
            ["pso-07"],
        ),
        _item(
            "pso-09",
            "application",
            "Prepare market analysis and systemic importance assessment",
            "finma",
            14,
            ["pso-07"],
        ),
        _item(
            "pso-10",
            "documentation",
            "Prepare participant documentation (rules and agreements)",
            "finma",
            21,
            ["pso-07"],
        ),
        # Risk management
        _item(
            "pso-11",
            "compliance",
            "Draft comprehensive risk management framework",
            "finma",
            21,
        ),
        _item(
            "pso-12",
            "compliance",
            "Prepare operational risk management (IT risk, cyber risk, BCP)",
            "finma",
            21,
            ["pso-11"],
        ),
        _item(
            "pso-13",
            "compliance",
            "Prepare settlement risk controls (finality and irrevocability)",
            "finma",
            14,
            ["pso-11"],
        ),
        _item(
            "pso-14",
            "compliance",
            "Prepare default management procedures",
            "finma",
            14,
            ["pso-11"],
        ),
        _item(
            "pso-15",
            "compliance",
            "Prepare credit and liquidity risk management (if applicable)",
            "finma",
            14,
            ["pso-11"],
        ),
        # Technical infrastructure
        _item(
            "pso-16",
            "it_operations",
            "Document system architecture and data flows",
            "finma",
            21,
        ),
        _item(
            "pso-17",
            "it_operations",
            "Prepare security framework and cybersecurity controls",
            "finma",
            21,
        ),
        _item(
            "pso-18",
            "it_operations",
            "Prepare BCP/DR documentation with RTOs/RPOs",
            "finma",
            14,
        ),
        _item(
            "pso-19",
            "it_operations",
            "Prepare operational resilience and redundancy measures",
            "finma",
            14,
        ),
        _item(
            "pso-20",
            "it_operations",
            "Document access control and change management procedures",
            "finma",
            7,
        ),
        # Financial requirements
        _item(
            "pso-21",
            "capital",
            "Prepare capital adequacy and financial guarantee documentation",
            "finma",
            14,
            ["pso-01"],
        ),
        _item(
            "pso-22",
            "capital",
            "Prepare audited financial statements",
            "finma",
            21,
            ["pso-21"],
        ),
        _item(
            "pso-23",
            "capital",
            "Document liquidity resources and insurance coverage",
            "finma",
            14,
        ),
        # Compliance & audit
        _item(
            "pso-24",
            "compliance",
            "Prepare AML/KYC procedures (if applicable, via SRO membership)",
            "finma",
            21,
        ),
        _item(
            "pso-25",
            "compliance",
            "Appoint FINMA-approved regulatory audit firm",
            "finma",
            14,
        ),
        _item(
            "pso-26",
            "compliance",
            "Set up internal audit function and compliance monitoring",
            "finma",
            14,
            ["pso-06"],
        ),
        # Application
        _item(
            "pso-27",
            "application",
            "Pre-notify FINMA via authorisation@finma.ch",
            "finma",
            7,
        ),
        _item("pso-28", "application", "Register on FINMA EHP platform", "finma", 1),
        _item(
            "pso-29",
            "application",
            "Submit complete application package via EHP",
            "finma",
            14,
            [
                "pso-05",
                "pso-08",
                "pso-11",
                "pso-16",
                "pso-22",
                "pso-25",
                "pso-28",
            ],
        ),
        _item(
            "pso-30",
            "application",
            "FINMA review and assessment period (6-12 months)",
            "finma",
            270,
            ["pso-29"],
        ),
    ]


def get_checklist_for_pathway(pathway: str) -> list[ChecklistItem]:
    if pathway == "sro":
        return get_sro_checklist()
    if pathway == "finma_securities":
        return get_securities_firm_checklist()
    if pathway == "finma_payment_systems":
        return get_payment_systems_checklist()
    if pathway.startswith("finma"):
        return get_finma_checklist()
    return []
